# This workflow will build a snapshot release daily
# and remove older releases
name: ci-snapshot

on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
        cache: maven

    - name: Build
      run: mvn -B package -Dquarkus.package.jar.type=uber-jar --file pom.xml

    - name: set release name
      id: set-release-name
      run: |
        echo "RELEASE_DATE=$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT

    - name: Publish Snapshot
      uses: softprops/action-gh-release@v2
      with:
        files: target/*-runner.jar
        prerelease: true
        make_latest: true
        generate_release_notes: false
        draft: false
        body: "This is a nightly snapshot for testing purposes."
        tag_name: ${{ steps.set-release-name.outputs.RELEASE_DATE }}-dev
        token: ${{ secrets.RELEASE }}

  find-older-snapshots:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    outputs:
      tags: ${{ steps.find-older-tags.outputs.tags }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: 'true'

    # checkout action is broken, so... https://github.com/actions/checkout/pull/2200
    - run: git fetch --tags

    - name: Find older snapshot tags
      id: find-older-tags
      run: |
        echo 'tags=["'$(git tag -l "*dev" | grep -v $(date +"%Y.%m.%d")  | xargs | sed -e 's/ /","/g')'"]' >> $GITHUB_OUTPUT
    - run: |
        echo 'Going to remove tags: ${{ steps.find-older-tags.outputs.tags }}'

  remove-older-snapshots:
    needs: find-older-snapshots
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        tag: ${{ fromJSON(needs.find-older-snapshots.outputs.tags) }}
    steps:
    - name: Remove older snapshot tags and releases
      uses: ClementTsang/delete-tag-and-release@v0.3.1
      with:
        delete_release: true
        tag_name: ${{ matrix.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE }}