# This workflow will build a snapshot release daily
# and remove older releases
name: ci-snapshot

on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
        cache: maven

    - name: Build
      run: mvn -B package -Dquarkus.package.jar.type=uber-jar --file pom.xml
      
    - name: Find older snapshot tags
      uses: ubuntu-latest
      run: echo 'TAGS=['$(git tag -l "*dev" | xargs | sed -e 's/ /,/g')']' >> $GITHUB_OUTPUT

    - name: Remove older snapshot tags and releases
      uses: ClementTsang/delete-tag-and-release@v0.3.1
      strategy:
        matrix:
          tag: ${{ fromJSON(TAGS) }}
      with:
        delete_release: true
        tag_name: ${{ matrix.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: set release name
      run: |
        echo "RELEASE_DATE=$(date +"%Y.%m.%d")" >> ${GITHUB_ENV}

    - name: Publish Snapshot
      uses: softprops/action-gh-release@v2
      with:
        files: target/*-runner.jar
        prerelease: true
        generate_release_notes: false
        tag_name: v.${{ RELEASE_DATE }}-dev
        token: ${{ secrets.RELEASE }}
